# Generated by Django 4.2.14 on 2024-08-13 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='pure_ai_response',
            field=models.TextField(default=datetime.datetime(2024, 8, 13, 19, 51, 0, 493523, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
