# Generated by Django 4.2.14 on 2024-08-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DietPlan', '__first__'),
        ('Plan', '0001_initial'),
        ('Meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='DietPlan.food'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='Plan.plan'),
        ),
    ]
