# Generated by Django 4.2.14 on 2024-08-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meal', '0002_meal_pure_ai_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_time',
        ),
    ]
