# Generated by Django 4.2.14 on 2024-08-15 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meal', '0003_remove_meal_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='pure_ai_response',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
    ]
