# Generated by Django 4.2.14 on 2024-08-07 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0001_initial'),
        ('Meal', '0003_alter_meal_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='Plan.plan'),
        ),
    ]
