# Generated by Django 4.2.14 on 2024-08-07 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
        ('Meal', '0004_alter_meal_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='Food.food'),
        ),
    ]
