# Generated by Django 4.2.14 on 2024-08-07 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Meal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_time', models.TimeField()),
                ('cook_time', models.TimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient_steps', models.TextField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='Meal.meal')),
            ],
        ),
    ]
