# Generated by Django 4.2.14 on 2024-08-06 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BodyTrait', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('diet_request', models.TextField()),
                ('diet_start_date', models.DateField()),
                ('diet_end_date', models.DateField()),
                ('body_trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='BodyTrait.bodytrait')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
