# Generated by Django 4.2.14 on 2024-08-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('calorie', models.FloatField()),
                ('meal_time', models.TimeField()),
                ('fat', models.FloatField()),
                ('carb', models.FloatField()),
                ('protein', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
